### ISSUE TITLE
Some routes are open for any user to accesss

### ISSUE THREAD

**Issue by cesarwelch** [CodeX-Academy-Official/codex.academy#65]
I manage to enter to some routes which I believe I shouldn't be able to.
Steps to reproduce: 

- go to the codex site, but use another route that might have a view linked to it, in this case "test"

This happen in all devices, and all browsers.

![image](https://user-images.githubusercontent.com/7519893/79033898-435d5d80-7b6f-11ea-9535-6bd921897a88.png)

[Video showing it](https://recordit.co/OQz5yCLNXB)

**Comment by cesarwelch** [comment]
Pretty much ALL routes doesn't have any validation, so I can enter em at any moment. could might dangerous.
![image](https://user-images.githubusercontent.com/7519893/79034743-e7e29e00-7b75-11ea-9d5c-516402531218.png)

**Comment by bsommardahl** [comment]
Great catch. I'll fix the demo academy page and let the others live. Not so dangerous because it's not to the user's advantage to skip steps. In the case of skipping the app fee, we would catch that later in the process. Besides, if they can hack the site and skip the app fee, maybe they deserve to have it waived. :)
